language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

before_deploy:
  - zip -r recipe-v2
  - mkdir -p deploy
  - mv recipe-v2.zip deploy/recipe-v2.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: seongbinko-kakao-bucket # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: seongbinko-kakao-bucket # S3 버킷
    key: recipe-v2.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: seongbinko-recipe-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: seongbinko-recipe-webservice-group # 웹콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wnrhd1082@gmail.com